### PR TITLE
I 3 users

### PR DESCRIPTION
**Pull request by yoshiemuranaka**
Adding different Vue components needed for local user page. Haven't tried modifying styles, just working with what is available out of the box.

### CODE REVIEW

**Comment by derick-montague** [comment]
Not sure why, but the add user modal cancel button does not close the modal.

**Comment by derick-montague** [comment]
If you update the PR to fix the cancel button, depending on which of the two PR's goes in first, I sorted the Plugin imports so that they are alphabetical, so there will end up being a conflict.

**Comment by yoshiemuranaka** [comment]
Starting to work with Axios. $http wrapper wasn't available in my store module. Probably need to make it globally accessible in Vuex Store, not sure the best way to do it

**Comment by derick-montague** [comment]
> Starting to work with Axios. $http wrapper wasn't available in my store module. Probably need to make it globally accessible in Vuex Store, not sure the best way to do it

Why don't we merge this and work with Axios in another PR. I did this in another branch regarding the store. I was planning to add an api.js file in the services directory for our all our api calls. For now though, you could just do it in the index.js file in the store directory in an action.

Here is a quick example: https://medium.com/dailyjs/mastering-vuex-zero-to-hero-e0ca1f421d45

We may not even need the $http method actually. I was just testing some examples and we should remove it for now.

**Comment by derick-montague** [comment]
Can I merge this?

**Review by derick-montague — APPROVED** [review]

**Review by gtmills — APPROVED** [review]

**Review by dixsie — APPROVED** [review]

**Comment by derick-montague** [comment]
Integrated into webui-vue in https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/28599

**Pull request merged**
